# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e44fd50d68d74ac5b08119c0ebdfa21c63f2acf3a869c9561f7afa8367236f5ef6b6e608bd38cf0d83c297cc6137251a391af95fde967d425f78650452d9e078

test:
  secret_key_base: 8c3921760b5d681c5ada91bbefde832e9bf1d9f4fdc631503561de11a306bba48bc69b7298cdf2512acebbe6e8d3a8618446ce5a11e2df6653b6e7890a542a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
